baseURL = 'https://0xbuilders.github.io/'

languageCode = 'es-ES'
defaultContentLanguage = 'es'

title = '0xBuilders page'
titleCaseStyle = '0xBs'

copyright = '© 2022 0xBuilders'

enableRobotsTXT = true
googleAnalytics = ""

pygmentsUseClasses = true

Paginate = 10

theme = 'basic'

[related]
threshold = 80.0
includeNewer = false
toLower = false
    [[related.indices]]
    name = "keywords"
    weight = 100.0
 
    [[related.indices]]
    name = "date"
    weight = 10.0

[permalinks]
posts = "posts/:year/:month/:slug/"
year = "/posts/:slug/"
month = "/posts/:slug/"

[taxonomies]
year = "year"
month = "month"
tag = "tags"
category = "categories"

[params]
author = "Blitty"
description = "0xBuilders webpage"

gh_organization = "https://api.github.com/orgs"
gh_org_DIY = "DIY-the-hard-way"
gh_org_0xbuilders = "0xbuilders"
